version: "3"
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - .:/color_sample
      - gem-data:/usr/local/bundle
    ports:
      - "3001:3001"
    stdin_open: true
    tty: true

volumes:
  gem-data:
    driver: local
